Traceback (most recent call last):
  File "mp_dist_trial.py", line 302, in <module>
    run_demo(setupAndCall, 4)
  File "mp_dist_trial.py", line 298, in run_demo
    join=True)
  File "/scratch/pm2758/anaconda3/envs/pytorch_v1/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 167, in spawn
    while not spawn_context.join():
  File "/scratch/pm2758/anaconda3/envs/pytorch_v1/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 114, in join
    raise Exception(msg)
Exception: 

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/scratch/pm2758/anaconda3/envs/pytorch_v1/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/scratch/pm2758/distTraining/Code/mp_dist_trial.py", line 277, in setupAndCall
    main(rank, world_size)
  File "/scratch/pm2758/distTraining/Code/mp_dist_trial.py", line 249, in main
    weighted_loss, numberOfSamples, average_time = run(rank, wsize, model, optimizer, criterion, epochs, trainLoader, bszTrain, devLoader, use_cuda)
  File "/scratch/pm2758/distTraining/Code/mp_dist_trial.py", line 149, in run
    num_batches = ceil(len(trainLoader.dataset) / float(bsz))
NameError: name 'ceil' is not defined

